export const DistrictArray = [
  { district: "Wendo", elder: "Elder Paul Thairu" },
  { district: "Utugi", elder: "Elder David Muiruri" },
  { district: "Ebenezer", elder: "Elder Peter Maina" },
  { district: "Witikio", elder: "Elder Wallace Kiarie" },
  { district: "Hekima", elder: "Elder Joseph Gacheru" },
  { district: "Mwangaza", elder: "Elder Eustace Kamande" },
  { district: "Kioneki", elder: "Elder Jacinta Njoga" },
  { district: "Emmanuel", elder: "Elder Stephen Ndegwa" },
  { district: "Utheri", elder: "Elder Richard Nderitu" },
  { district: "Thayu", elder: "Elder Carol Nguru" },
  { district: "Tumaini", elder: "Elder Isaac Gachuiga" },
  { district: "Jerusalem", elder: "Elder Isaac Kimotho" },
  { district: "Bethesda", elder: "Elder David Mwangi" },
  { district: "Githima", elder: "Elder Samuel Macharia" },
  { district: "Baraka", elder: "Elder Zackariah Kori" },
  { district: "Shammah", elder: "Elder Simon Kigotho" },
  { district: "Ushindi", elder: "Elder John Kihumba" },
  { district: "Kirigiriro", elder: "Elder Joseph Mugweru" },
  { district: "Kirathimo", elder: "Elder Ann Njoroge" },
  { district: "Highway", elder: "Elder Grace Benson" },
  { district: "Macedonia", elder: "Elder Antony Maina" },
  { district: "Munyaka", elder: "Elder Ruth Wanjeri" },
  { district: "Kioneki", elder: "Elder Stephen Kanyi" },
];
